/**
 * @type {import("prettier").Config}
 */
module.exports = {
    useTabs: false,
    printWidth: 140,
    tabWidth: 4,
    semi: false,
    singleQuote: true,
    trailingComma: 'all',
    plugins: ['@ianvs/prettier-plugin-sort-imports'],
    importOrder: [
        '<BUILTIN_MODULES>',
        '',
        '<THIRD_PARTY_MODULES>',
        '',
        '^@diia-inhouse/diia-app$',
        '',
        '^@diia-inhouse/.*$',
        '',
        '^@src/.*$',
        '',
        '^@actions/.*$',
        '',
        '^@services/.*$',
        '',
        '^@providers/.*$',
        '',
        '^@models/.*$',
        '',
        '^@dataMappers/.*$',
        '',
        '^@utils$',
        '',
        '^@utils/.*$',
        '',
        '^@mocks/.*$',
        '',
        '^@tests/.*$',
        '',
        '^@interfaces/.*$',
        '',
        '^[./]',
        '',
    ],
    importOrderTypeScriptVersion: '5.0.0',
    importOrderCaseSensitive: true,
}
